// <auto-generated />
using System;
using FiTrack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FiTrack.Migrations
{
    [DbContext(typeof(FiTrackContext))]
    [Migration("20190322191919_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FiTrack.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MealId");

                    b.Property<string>("name");

                    b.Property<string>("ndbno");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("FiTrack.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories");

                    b.Property<DateTime>("MealDate");

                    b.Property<DateTime>("MealTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Meal");
                });

            modelBuilder.Entity("FiTrack.Models.Food", b =>
                {
                    b.HasOne("FiTrack.Models.Meal")
                        .WithMany("FoodComponents")
                        .HasForeignKey("MealId");
                });
#pragma warning restore 612, 618
        }
    }
}
